services:
  my-app:
    build: .
    image: my-script:hw2
    container_name: my-app
    init: true
    restart: "no"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /mnt/logs/my-app:/var/www
